### ISSUE TITLE
How can raw data be processed to use your algorithm?

### ISSUE THREAD

**Issue by fengyanpin** [jingxiaoliu/TelecomTM#1]
Hello, I am a graduate student, recently learned DAS vehicle detection algorithm, my original data signal-to-noise ratio is very low, how should I deal with it?

**Comment by jingxiaoliu** [comment]
Hi,

Thanks for the question. I would suggest you try different filters (e.g., median filter) and general signal processing approaches to remove temporal and spatial noises. Also, you can use some advanced data-driven approach to improve the SNR, such as: https://arxiv.org/pdf/2212.03936.pdf

Best,
Jingxiao

**Comment by fengyanpin** [comment]
Thank you very much for taking time out of your busy schedule to answer me. The data sampling frequency adopted in your paper is 250HZ. May I ask if you conducted downsampling before processing? My data is the sampling data of the communication fiber of the highway, the sampling rate is 500HZ, how much HZ is the lower sampling to facilitate the observation of clear lines?

**Comment by jingxiaoliu** [comment]
Hi, for quasi-static signals (ground deformation due to vehicle self-weight), we used 0.1 ~ 1 Hz. for surface wave signals, we used signals greater than 3 Hz.
